import {useEffect} from 'react';
import {useRoute} from '@react-navigation/native';

type SelectionCallback<T = any> = (data: T) => void;

// Global memory Map storing callbacks (key is the route.key of the owner page)
const callbackMap = new Map<string, SelectionCallback>();

/**
 * Register a callback under an ownerId (which is the route.key).
 */
export function registerSelectCallback(
  ownerId: string,
  cb: SelectionCallback,
): void {
  callbackMap.set(ownerId, cb);
}

/**
 * Emit selected data for a given callbackId.
 */
export function emitSelectResult<T = any>(
  callbackId: string,
  data: T,
): boolean {
  const cb = callbackMap.get(callbackId);
  if (!cb) {
    return false;
  }
  cb(data);
  callbackMap.delete(callbackId);
  return true;
}

/**
 * Automatically locate the previous screen's key in the navigation stack
 * and emit the selection result to it.
 */
export function emitSelectResultToPrevRoute<T = any>(
  navigation: any,
  data: T,
): boolean {
  const state = navigation.getState();
  if (!state || !state.routes) {
    return false;
  }
  const prevRoute = state.routes[state.routes.length - 2];
  if (!prevRoute) {
    return false;
  }
  return emitSelectResult(prevRoute.key, data);
}

/**
 * Clear the callback registered by a specific ownerId.
 */
export function clearSelectResultsForOwner(ownerId: string): void {
  callbackMap.delete(ownerId);
}

/**
 * Custom React Hook for components initiating a selection flow.
 * Automatically obtains the screen instance key and manages lifecycle cleanup.
 */
export function useSelectBridge<T = any>() {
  const route = useRoute();
  const ownerId = route.key; // Unique key generated by React Navigation for this screen

  // Cleanup pending callback when the component unmounts
  useEffect(() => {
    return () => {
      clearSelectResultsForOwner(ownerId);
    };
  }, [ownerId]);

  const registerSelect = (cb: SelectionCallback<T>): void => {
    registerSelectCallback(ownerId, cb);
  };

  return {registerSelect};
}
